# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - worksheetinator

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Install dependencies
        run: npm install
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B2D704CC75C4032A8EA3F95360C70B3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0EEB6E182BF0486C81287AA0AAE73CC9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0F2B9927D40F49F0ABBF4FF9CEA747A1 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'worksheetinator'
          slot-name: 'Production'
          package: ./src
          